variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  paths:
    - "${PIP_CACHE_DIR}"

stages:
  - test
  - build

before_script:
  - pip install -r requirements/requirements-build.txt

validate-test-py38:
  stage: test
  image: python:3.8
  script:
    - tox -e py38

validate-test-py39:
  stage: test
  image: python:3.9
  script:
    - tox -e py39

validate-test-py310:
  stage: test
  image: python:3.10
  script:
    - tox -e py310

dist-build-publish:
  stage: build
  image: python:3.9
  needs:
    - validate-test-py38
    - validate-test-py39
    - validate-test-py310
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    REPO_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  script:
    - bash devops/scripts/build.sh
    - bash devops/scripts/dist-publish.sh
