variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  paths:
    - "${PIP_CACHE_DIR}"

stages:
  - test
  - build

before_script:
  - pip install -r requirements/requirements-build.txt

validate-test-py38:
  image: python:3.8
  stage: test
  only:
    - tags
  script:
    - tox -e py38
  artifacts:
    when: always
    reports:
      junit: junit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

validate-test-py39:
  image: python:3.9
  stage: test
  only:
    - tags
  script:
    - tox -e py39
  artifacts:
    when: always
    reports:
      junit: junit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

dist-build-publish:
  image: python:3.9
  stage: build
  only:
    - tags
  needs:
    - validate-test-py38
    - validate-test-py39
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    REPO_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  script:
    - bash devops/scripts/build.sh
    - bash devops/scripts/dist-publish.sh
