#!/usr/bin/env bash

export PATH=/app/venv/bin:${PATH}

echo "Running entrypoint for ${1} ..."

case "${1}" in
run)
    exec "run-${1}" --bind "0.0.0.0:8000" -w gunicorn
    ;;
esac

exec bash --login
